- .github/workflows/rust.yml
- .gitignore
- rust-toolchain
Round 2, this replaces #2, just adding the workflow file, `rust-toolchain`, and branching off of `main` instead.  no other changes.
> Add CI Workflow

- rsky-feedgen/Cargo.toml
- rsky-firehose/Cargo.toml
- rsky-firehose/src/car.rs
- rsky-firehose/src/firehose.rs
- rsky-firehose/src/main.rs
- rsky-lexicon/Cargo.toml
- rsky-lexicon/src/com/atproto/repo.rs
- rsky-lexicon/src/com/atproto/sync.rs
closes #9
this appears to compile and pass checks, without having to do much other than swapping out the libraries.
> `use libipld::cid::Cid`

- rsky-pds/src/apis/com/atproto/server/mod.rs
- rsky-pds/src/main.rs
- rsky-pds/src/plc/mod.rs
- rsky-pds/src/plc/operations.rs
- rsky-pds/src/plc/types.rs
Remove tag from PLC op enum, serialize prev even when null and ensure op is ordered correctly during serialization. Fixes #25 
Also ensures that the same environment variable is used throughout.
> PLC Client: Properly Serialize Update Op

- rsky-pds/src/apis/com/atproto/admin/update_subject_status.rs
- rsky-pds/src/apis/com/atproto/repo/apply_writes.rs
- rsky-pds/src/apis/com/atproto/repo/create_record.rs
- rsky-pds/src/apis/com/atproto/repo/delete_record.rs
- rsky-pds/src/apis/com/atproto/repo/get_record.rs
- rsky-pds/src/apis/com/atproto/repo/list_records.rs
- rsky-pds/src/apis/com/atproto/repo/put_record.rs
- rsky-pds/src/repo/mod.rs
- rsky-pds/src/repo/record/mod.rs
- rsky-pds/src/repo/types.rs
- rsky-syntax/src/aturi.rs
closes #36 
This PR implements the [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) trait for `AtUri` to handle string-to-AtUri conversions. This addresses multiple TODOs throughout the codebase where string manipulation was being used instead of proper AtUri types.
Files modified:
- src/apis/com/atproto/admin/update_subject_status.rs
- src/apis/com/atproto/repo/apply_writes.rs
- src/apis/com/atproto/repo/create_record.rs
- src/apis/com/atproto/repo/delete_record.rs
- src/apis/com/atproto/repo/get_record.rs
- src/apis/com/atproto/repo/list_records.rs
- src/apis/com/atproto/repo/put_record.rs
- src/repo/mod.rs
- src/repo/record/mod.rs
- src/repo/types.rs
- src/syntax/aturi.rs
The core change is implementing TryFrom for AtUri with three variants:
```rust
impl …
```
> Imlementation of AtUri proposal

- rsky-pds/src/account_manager/helpers/email_token.rs
- rsky-pds/src/apis/com/atproto/server/mod.rs
- rsky-pds/src/common/time.rs
Current token validation behavior causes tokens to always be expired as the token is measured in seconds, but the comparison uses microseconds.  This fixes that issue.
In addition, the bsky client doesn't allow for certain characters in the token value, so have removed those from possible values to allow for support.
> BugFix:Token Validation

- rsky-jetstream-subscriber/src/jetstream.rs
- rsky-jetstream-subscriber/src/main.rs
Ran Clippy on Jetstream and removed unused imports. It was merged in before the latest pipeline updates so it skipped some checks that have now been properly implemented. No new features or changes otherwise
N/A
> RSky-Jetstream-Subscriber: Code Cleanup

- Cargo.toml
- rsky-lexicon/Cargo.toml
- rsky-lexicon/src/com/atproto/identity.rs
- rsky-pds/src/account_manager/mod.rs
- rsky-pds/src/apis/com/atproto/identity/mod.rs
- rsky-pds/src/apis/com/atproto/identity/sign_plc_operation.rs
- rsky-pds/src/main.rs
This implements the Sign PLC Operation API endpoint. This is necesary for any case where a user wants us to sign a given PLC operation, but not necessarily use it right away. Examples include, but are not limited to, if a user wants to migrate away from our PDS
> PDS: Implemented Sign PLC Operation API

- ROADMAP.md
This PR updates our v1.0.0 roadmap to emphasize our commitment to cloud-native best practices by:
1. Adding a dedicated "Production Readiness" section and a row in the table.
>  Incorporate Production Readiness into Roadmap

- rsky-satnav/Cargo.toml
- rsky-satnav/src/main.rs
Added diffing support to rsky-satnav. The user can open 2 car files now & see the diffs in terms of blocks & actual records. I've also added onHover handler to use blue highlight for the previous block & red highlight for the next block to make it easy to navigate. This does not check if the car files have any common history yet.
> rsky-satnav: add diff UI

- rsky-relay/src/crawler/worker.rs
- rsky-relay/src/publisher/worker.rs
- rsky-relay/src/validator/manager.rs
Messed up the the polling interest flags. We only need to know if the crawling connection is "readable" & the publishing connection is "writable". A connection is almost always writable, so epoll keeps waking up crawling threads for no reason. Should cut down CPU usage of crawling from 400% to 5%.
> rsky-relay: fix polling interest

- rsky-relay/Cargo.toml
- rsky-relay/src/crawler/manager.rs
- rsky-relay/src/validator/manager.rs
Use a separate SQLite DB for storing host state (& later on repo state as well). This allows us to easily debug the state for different hosts & also allows us to manually change the cursor or remove an entry completely to allow it to continue from present.
TODO (later on): switch to a query builder or sqlx/diesel for this.
> rsky-relay: use sqlite for host state

- rsky-relay/src/main.rs
- rsky-relay/src/validator/utils.rs
Some cases, which are allowed to pass-through in the indigo relay are currently getting blocked by our relay. Update the verification behavior to bring it inline with indigo relay.
> rsky-relay: fix false negatives for commit verification

- rsky-relay/Cargo.toml
- rsky-relay/src/main.rs
Use file-rotate so that the logs are compressed after rotation to save disk space.
> rsky-relay: switch to file-rotate for compressed logs

- .github/workflows/ghcr.yml
- rsky-pds/Dockerfile
1. Modified rsky-pds/Dockerfile to use multi-stage builds like the jetstream subscriber, while preserving the
environment variables in the CMD
2. Created .github/workflows/ghcr.yml that will publish the Docker images to ghcr.io for the blacksky-algorithms
organization
The workflow will trigger when changes are pushed to main branch that affect any of the three services, or
manually via workflow_dispatch. It builds and pushes each Docker image with appropriate tags based on the git
reference.
I'm trying to build an rsky-pds instance in k8s.
> new image workflow to upload to ghcr

- rsky-relay/src/server/server.rs
I always get a HTTP 502 response at https://atproto.africa in Firefox, and while I can load the http page in Safari, attempting a websocket connection leads it to also recieving a 502.
In narrowing down the cause with cURL, I found that it was not any specific browser header that was problematic, but the total number of them. My install of Firefox sends more headers than Safari, explaining why it fails while Safari works, and websocket connections add two additional headers, explaining why Safari works for the HTTP request but not the websocket upgrade.
Note that the live server appears to run behind caddy, which adds at least three extra request headers by default (X-Forwarded-*).
This change upgrades the allocated request headers for parsing from 16 -> 32, which is hopefully enough to …
> Increase request headers limit (browser HTTP 502s)

- rsky-relay/Cargo.toml
- rsky-relay/src/crawler/client.rs
- rsky-relay/src/crawler/connection.rs
- rsky-relay/src/crawler/manager.rs
- rsky-relay/src/crawler/mod.rs
- rsky-relay/src/crawler/types.rs
- rsky-relay/src/crawler/worker.rs
- rsky-relay/src/main.rs
- rsky-relay/src/publisher/manager.rs
- rsky-relay/src/publisher/types.rs
- rsky-relay/src/publisher/worker.rs
- rsky-relay/src/server/server.rs
- rsky-relay/src/validator/manager.rs
Added various changes to enable connecting to all PDSes:
- persisted host state on a timer
- retry on host sqlite locked error
- add connect/reconnect backoff
- TODO: add logic to clear retry once we've a stable connection
- TODO: persist retry state to DB
- use non-blocking connect for crawler
- Without this, the crawler worker can get blocked while we're trying to connect & do a handshake
- With this, we can have try connecting to new hosts without blocking everything
- increased queue sizes to accommodate more hosts
> rsky-relay: connect to everything

- Cargo.toml
- rsky-relay/Cargo.toml
- rsky-relay/src/config.rs
- rsky-relay/src/crawler/connection.rs
- rsky-relay/src/main.rs
- rsky-relay/src/server/server.rs
- rsky-relay/src/types.rs
- rsky-relay/src/validator/event.rs
- rsky-relay/src/validator/manager.rs
- rsky-relay/src/validator/mod.rs
- rsky-relay/src/validator/resolver.rs
- rsky-relay/src/validator/types.rs
- rsky-relay/src/validator/utils.rs
- I've opted to use a feature flag to allow us to run a separate relay in labeler mode. It was the easiest way to implement a labeler relay, since we don't need separate book keeping for repo relay & labeler relay.
- Added out-of-spec `com.atproto.label.requestCrawl` similar to `com.atproto.sync.requestCrawl`
- It will require spinning up a separate service & using separate path on the domain or path based routing to allow running on the same domain.
Closes #120
> rsky-relay: add labeler relay

- rsky-feedgen/Dockerfile
- rsky-firehose/Dockerfile
- rsky-jetstream-subscriber/Dockerfile
- rsky-pds/Dockerfile
Does a git clone instead of copying every workspace member in the dockerfile.  This prevents a brittle dockerfile specification and something agnostic towards all dockerfile implementations.
Closes #126
> updating first version of the dockerfile improvement

- rust-toolchain
The aws dependencies need at least Rust 1.86, hence use that version. A nightly release is not needed, hence use this stable release instead.
Closes #134.
> Upgrade to Rust 1.86

- Cargo.lock
- rsky-common/Cargo.toml
- rsky-common/src/ipld.rs
`ipld-core` isn't used anywhere within the `rsky-common` crate, hence remove it from the dependencies.
> rsky-common: ipld-core dependency is not needed

- Cargo.lock
- rsky-feedgen/Cargo.toml
- rsky-feedgen/Dockerfile
- rsky-feedgen/migrations/2025-09-25-023708-0000_tsvector_index/down.sql
- rsky-feedgen/migrations/2025-09-25-023708-0000_tsvector_index/up.sql
- rsky-feedgen/src/apis/mod.rs
- rsky-feedgen/src/routes.rs
- rsky-pds/Cargo.toml
Use [diesel_full_text_search](https://github.com/diesel-rs/diesel_full_text_search) for hashtag search.
SQL equivalent for hashtag query example:
```sql
SELECT * FROM public.post WHERE to_tsvector('simple', text) @@ to_tsquery('simple', '#blackskytravel | #blackademics');
```
https://github.com/blacksky-algorithms/rsky/issues/91
> feat: add feedgen text search
